# Generated by Django 3.2.7 on 2023-11-29 09:22

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("address", models.CharField(max_length=256)),
                ("address_2", models.CharField(blank=True, max_length=256)),
                ("city", models.CharField(max_length=256)),
                ("post_code", models.CharField(max_length=8)),
                (
                    "country",
                    django_countries.fields.CountryField(default="GB", max_length=2),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("number", models.CharField(max_length=15)),
            ],
        ),
    ]
