# Generated by Django 4.2.7 on 2023-12-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_lab"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodtestresults",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.lab",
            ),
        ),
    ]
